name: CI
on:
  pull_request: {}
jobs:
  docker-build-push:
    name: Docker Build/Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Log in to Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          install: true
      - name: Docker build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          cache-from: type=registry,ref=uncledrewbie/docker-cache-export-repro:buildcache
          cache-to: type=registry,ref=uncledrewbie/docker-cache-export-repro:buildcache,mode=max
          tags: |
            uncledrewbie/docker-cache-export-repro:latest
